package net.splakra.permitsanddiplomas.config;

import java.util.List;

public class ItemEntries {
    public static final List<List<String>> allItemEntries = List.of(
            List.of("Wool", "minecraft:white_wool", "minecraft:white_carpet"),
            List.of("Decorative Plants", "minecraft:dandelion"),
            List.of("Candles", "minecraft:candle"),
            List.of("Clay", "minecraft:clay_ball", "minecraft:clay"),
            List.of("Item Frames", "minecraft:item_frame", "minecraft:glow_item_frame", "create:placard"),
            List.of("Sugar Cane", "minecraft:sugar_cane"),
            List.of("Glazed Terracotta", "minecraft:orange_glazed_terracotta"),
            List.of("Prismarine", "minecraft:prismarine_shard", "minecraft:prismarine_crystals", "minecraft:prismarine", "minecraft:prismarine_bricks", "minecraft:dark_prismarine", "minecraft:sea_lantern"),
            List.of("Lapis", "minecraft:lapis_lazuli", "minecraft:lapis_block"),
            List.of("Amethysts", "minecraft:amethyst_shard", "minecraft:amethyst_block", "minecraft:amethyst_cluster"),
            List.of("Glowstone", "minecraft:glowstone_dust", "minecraft:glowstone"),
            List.of("Bricks", "minecraft:brick", "minecraft:bricks"),
            List.of("Paintings", "minecraft:painting"),
            List.of("Bamboo", "minecraft:bamboo", "minecraft:bamboo_block", "minecraft:bamboo_planks", "minecraft:scaffolding"),
            List.of("Crops", "minecraft:wheat", "minecraft:carrot", "minecraft:potato", "minecraft:beetroot", "minecraft:pumpkin", "minecraft:melon"),
            List.of("Light Sources", "minecraft:torch", "minecraft:lantern", "minecraft:campfire", "minecraft:ochre_froglight", "minecraft:shroomlight", "minecraft:end_rod", "create:rose_quartz_lamp"),
            List.of("Glass", "minecraft:glass", "minecraft:glass_pane", "create:framed_glass"),
            List.of("Paper", "minecraft:paper"),
            List.of("Potions", "minecraft:potion", "minecraft:glass_bottle", "minecraft:blaze_powder", "minecraft:magma_cream", "minecraft:nether_wart", "minecraft:spider_eye",
                    "minecraft:fermented_spider_eye", "minecraft:sugar", "minecraft:rabbit_foot", "minecraft:glistering_melon_slice", "minecraft:ghast_tear"),
            List.of("Concrete", "minecraft:gray_concrete_powder", "minecraft:gray_concrete"),
            List.of("Belts and Chains", "create:belt_connector", "minecraft:chain"),
            List.of("Dyes", "minecraft:purple_dye"),
            List.of("Gravel", "minecraft:gravel"),
            List.of("Sand", "minecraft:sand"),
            List.of("Fluid Stuff", "create:fluid_pipe", "create:fluid_tank", "create:mechanical_pump", "create:copper_valve_handle", "create:fluid_valve",
                    "create:smart_fluid_pipe", "create:item_drain", "create:spout", "create:hose_pulley", "create:portable_fluid_interface", "create:steam_engine"),
            List.of("Hostile Mob Drops", "minecraft:bone", "minecraft:string", "minecraft:rotten_flesh", "minecraft:gunpowder", "minecraft:spider_eye", "minecraft:blaze_rod", "minecraft:ender_pearl", "minecraft:ghast_tear"),
            List.of("Basic Nether Blocks", "minecraft:netherrack", "minecraft:nether_bricks", "minecraft:basalt", "minecraft:blackstone", "minecraft:warped_nylium",
                    "minecraft:warped_stem", "minecraft:crimson_nylium", "minecraft:crimson_stem", "minecraft:magma_block", "minecraft:soul_sand", "minecraft:soul_soil"),
            List.of("Train Components", "create:track", "create:railway_casing", "create:schedule", "create:track_station", "create:track_signal", "create:track_observer", "create:controls"),
            List.of("Packages", "create:cardboard", "create:package_frogport", "create:packager"),
            List.of("Quartz", "minecraft:quartz", "minecraft:quartz_block"),
            List.of("Enchanted Books", "minecraft:enchanted_book"),
            List.of("Rose Quartz", "create:electron_tube", "create:polished_rose_quartz", "create:rose_quartz_lamp", "create:display_board"),
            List.of("Precision Mechanisms", "create:precision_mechanism"),
            List.of("Honey and Slime", "minecraft:honeycomb", "minecraft:honey_bottle", "minecraft:honey_block", "minecraft:honeycomb_block", "create:honey_bucket", "minecraft:slime_ball", "minecraft:slime_block", "create:super_glue"),
            List.of("Enchanting Bottles", "minecraft:experience_bottle", "create_enchantment_industry:hyper_experience_bottle"),
            List.of("Gears and Gearboxes", "create:cogwheel", "create:large_cogwheel", "create:gearbox", "create:shaft"),
            List.of("Copper", "minecraft:copper_ingot", "minecraft:copper_block", "create:copper_sheet"),
            List.of("Zinc", "create:zinc_ingot", "create:zinc_block"),
            List.of("Gold", "minecraft:gold_ingot", "minecraft:gold_block", "create:golden_sheet"),
            List.of("Iron", "minecraft:iron_ingot", "minecraft:iron_block", "create:iron_sheet"),
            List.of("Brass", "create:brass_ingot", "create:brass_block", "create:brass_sheet", "create:brass_hand"),
            List.of("Equipment", "minecraft:netherite_pickaxe", "minecraft:diamond_axe", "minecraft:diamond_helmet", "minecraft:diamond_chestplate", "minecraft:diamond_leggings",
                    "minecraft:diamond_boots", "minecraft:diamond_sword", "minecraft:shield", "minecraft:totem_of_undying", "minecraft:bow", "minecraft:arrow", "minecraft:trident", "create:goggles", "create:wrench"),
            List.of("Vaults", "create:item_vault", "create:item_hatch", "create_redstone_requester"),
            List.of("Shulker Boxes", "minecraft:shulker_shell", "minecraft:shulker_box"),
            List.of("Rockets", "minecraft:firework_rocket"),
            List.of("Andesite Alloy", "create:andesite_alloy", "create:andesite_alloy_block"),
            List.of("Food", "minecraft:bread", "minecraft:golden_carrot", "minecraft:baked_potato", "minecraft:cooked_beef", "minecraft:cooked_chicken", "minecraft:cooked_cod", "minecraft:cookie",
                    "minecraft:cake", "minecraft:pumpkin_pie", "create:bar_of_chocolate", "create:sweet_roll", "create:chocolate_glazed_berries", "create:honeyed_apple", "create:builders_tea"),
            List.of("All Wood Blocks", "minecraft:spruce_log", "minecraft:spruce_planks", "minecraft:spruce_slab", "minecraft:spruce_slab", "minecraft:spruce_trapdoor", "minecraft:spruce_fence", "minecraft:barrel", "minecraft:chest"),
            List.of("All Stone Types", "minecraft:cobblestone", "minecraft:cobblestone_stairs", "minecraft:cobblestone_slab", "minecraft:cobblestone_wall"),
            List.of("Redstone Bits", "minecraft:redstone", "minecraft:redstone_block", "minecraft:redstone_torch", "minecraft:redstone_lamp", "minecraft:repeater", "minecraft:comparator", "minecraft:stone_button", "minecraft:lever",
                    "minecraft:oak_pressure_plate", "minecraft:piston", "minecraft:sticky_piston", "minecraft:observer", "minecraft:daylight_detector", "minecraft:target", "minecraft:rail", "minecraft:powered_rail", "minecraft:minecart"),
            List.of("Stock Factory", "create:stock_link", "create:stock_ticker", "create:factory_gauge"),
            List.of("Architecture", "create:crafting_blueprint"),
            List.of("Andesite Machines", "create:mechanical_drill", "create:mechanical_saw", "create:deployer", "create:mechanical_harvester", "create:mechanical_bearing", "create:encased_fan", "create:millstone",
                    "create:mechanical_press", "create:mechanical_mixer", "create:basin", "create:depot", "create:weighted_ejector", "create:portable_storage_interface")
    );
}
